### ISSUE TITLE
Consider not using type annotations when easy to infer

### ISSUE THREAD

**Issue by sethladd** [miketraverso/devfest_florida_app#1]
First off, AWESOME!

Second, here's something to consider but definitely not mandatory:

In many cases, you don't need to use a type annotation, the variable type will be inferred.

For example: `final String kAppTitle = 'DevFest Florida';` can be simply `final kAppTitle = 'DevFest Florida';`

final variables are, well, final and when you initialize them right at the declaration, especially with a literal, it's easy for the analyzer and the reader to infer.

**Comment by miketraverso** [comment]
Ah thanks! Good point. Will make those updates. New to Dart so that's the Java/ObjC in me. :)

**Comment by miketraverso** [comment]
d035a0e  Closing...
